# permissions for end users to view flowcollectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flowcollector-viewer-role
rules:
- apiGroups:
  - flows.netobserv.io
  resources:
  - flowcollectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flows.netobserv.io
  resources:
  - flowcollectors/status
  verbs:
  - get
