log-level: error
pipeline:
  ingest:
    type: file
    file:
      filename: ../../contrib/benchmarks/baseline/log-lines.json
      decoder:
        type: json
  encode:
    type: none
  extract:
    type: none
  transform:
    - type: generic
      generic:
        rules:
        - input: Bytes
          output: bytes
        - input: DstAddr
          output: dstAddr
  write:
    type: none

