apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflowsimulator
  labels:
    app: netflowsimulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflowsimulator
  template:
    metadata:
      labels:
        app: netflowsimulator
    spec:
      containers:
        - name: netflowsimulator
          image: networkstatic/nflow-generator:latest
          args:
            - "--target=$(FLOWLOGS_PIPELINE_SERVICE_HOST)"
            - "--port=$(FLOWLOGS_PIPELINE_SERVICE_PORT_NETFLOW_LEGACY)"
            - "--spike=http"
          imagePullPolicy: Always