log-level: debug
pipeline:
  - name: ingest_kafka
  - name: encode_kafka
    follows: ingest_kafka
parameters:
  - name: ingest_kafka
    ingest:
      type: kafka
      kafka:
        brokers: ["192.168.56.103:9092"]
        topic: topic1
        groupid: group1
        decoder:
          type: json
  - name: encode_kafka
    encode:
      type: kafka
      kafka:
        address: 192.168.56.103:9092
        topic: topic2

